env:
  browser: true
extends:
  - standard-with-typescript
  - plugin:promise/recommended
  - plugin:compat/recommended
  - prettier
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - compat
  - import
  - promise
ignorePatterns:
  - Live2dSdk/**/*
rules:
  no-unused-vars: off
  "@typescript-eslint/no-unused-vars":
    - warn
    - destructuredArrayIgnorePattern: "^_"
      argsIgnorePattern: "^_"
  "@typescript-eslint/no-misused-promises":
    - error
    - checksVoidReturn: false
  "@typescript-eslint/consistent-type-assertions": off
  new-cap: off
  import/order: # ref: https://chaika.hatenablog.com/entry/2022/05/15/150000
    - error
      # Order by group
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - object
        - type
        - index
      # no extra newlines between imports
      newlines-between: never
      pathGroupsExcludedImportTypes:
        - builtin
      alphabetize:
        order: asc
        caseInsensitive: true
      pathGroups:
        # pull up react-related
        - pattern: 'react**'
          group: external
          position: before
        # put css modules in the bottom
        - pattern: './**.module.css'
          group: index
          position: after
